### PR TITLE
Evaluate GitHub review capabilities -- edited the title

### PR DESCRIPTION
**Pull request by dlrdave**
Checkout the review features of github using this pull request

### CODE REVIEW

**Comment by dlrdave** [comment]
What happens if I mention @abellettre and @will2142 in a comment?

**Comment by Will-McMahan** [comment]
We get emails. 

```
 On Tuesday, May 12, 2015 10:15 AM, David Cole <notifications@github.com> wrote:
```

 What happens if I mention @abellettre and @will2142 in a comment?—

**Comment by abellettre** [comment]
I get one too
Alex

**Comment by dlrdave** [comment]
Closing. Evaluation over. GitHub wins.

**Pull request closed without merging**
